### PR TITLE
Apply async-await form and bump up node-slack-sdk@5.0.1

### PR DESCRIPTION
**Pull request by d3m3vilurr**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
I forgot index.js

**Comment by d3m3vilurr** [comment]
Just tested simple integration test. I'll use it next week and will share the result.

**Comment by d3m3vilurr** [comment]
looks work well now. :)

**Comment by thomas-profitt** [comment]
I'll admit I have only read over, not tested, the changes, but the code quality is clearly improved significantly; thank you again :)

**Pull request merged**
