### PR TITLE
Make prefix configurable

### LINKED ISSUE #34: Our "@slack_" reserved mxid prefix conflicts with matrix-appservice-slack's, causing the bridge to be unable to create Matrix ghost users if matrix-appservice-slack is also running
When the bridge has to create a new Slack user on the Matrix side (sometimes it doesn't in my deployment since it picks the same usernames as matrix-appservice-slack), I get this error:

```
Error in handleThirdPartyRoomMessage { [M_UNKNOWN: No row found]
  errcode: 'M_UNKNOWN',
  name: 'M_UNKNOWN',
  message: 'No row found',
  data: { errcode: 'M_UNKNOWN', error: 'No row found' },
  httpStatus: 404 } { roomId: '<removed>',
  senderId: '<removed>',
  senderName: '<removed>',
  avatarUrl: 'https://avatars.slack-edge.com/<removed>',
  text: '<removed>',
  html: '
removed
' } ﻿
```

### PR DESCRIPTION
**Pull request by jeffcasavant**
This moves the prefix into the config file.  I'm currently running this code with no ill effects, it's still able to forward messages and create rooms & ghost users with no problem.

Fixes #34

### CODE REVIEW

**Comment by thomas-profitt** [comment]
I'm really glad to finally see this!

There's two problems left to solve:
- We may need a way to make it clear that once the bridge has been running, creating rooms and users, its prefix can't be changed. A comment in config.json would do, if JSON supported comments.
- If a matrix-puppet-slack user upgrades to a version with this merged, they'd need to edit their existing config to get their bridge to work again. We need a way to default to the current "slack" for users who don't have a prefix configured (e.g., check if it exists in config and write it if not)

**Comment by jeffcasavant** [comment]
@thomas-profitt thoughts?

**Comment by thomas-profitt** [comment]
The only concern I have is the need to check `config.prefix === undefined ? 'slack' : config.prefix` each time `config.prefix` needs to be fetched; I can see future developers, who have their config set, just using `config.prefix`, and it working fine for them, but actually creating a fairly nasty state disenfragmentortion for users who don't have config.prefix set.

We could add something to startup to rewrite the config file to set config.prefix for users who don't have it, and then later in execution safely assume it's not null.

We could also abstract `config` so it's an object that's got defaults to extend the state in the JSON.

**Comment by jeffcasavant** [comment]
I'll hop back on this this week sometime.

**Comment by jeffcasavant** [comment]
@thomas-profitt sorry it took me so long to get back to this.

I went the migration-in-place route.  If the process is started with a config file that's missing the `prefix` key, it sets it to `'slack'` and writes `config.json` (neatly indented with 4 spaces).  It then terminates the process and requests the user start it again.

If it has any issues writing the file, it has already logged the key and value it was going to set, so it logs that error and crashes expecting the user to manually edit `config.json` to include the new values.

**Comment by thomas-profitt** [comment]
Good thinking!

Thanks for coming back to this :+1:

**Pull request merged**
